export const LOGIN = "LOGIN";
export const UPDATE_CRYPTO_LIST = "UPDATE_CRYPTO_LIST";
export const UPDATE_CRYPTO_DETAILS = "UPDATE_CRYPTO_DETAILS";
export const CLEAR_CRYPTO_DETAILS = "CLEAR_CRYPTO_DETAILS";